// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55bEINystWICTNVd25nZI7Zodk9WCCYs',
    appId: '1:286265416101:web:f3d1ef2cba8ce1a3df304c',
    messagingSenderId: '286265416101',
    projectId: 'bahias-2ea5b',
    authDomain: 'bahias-2ea5b.firebaseapp.com',
    storageBucket: 'bahias-2ea5b.firebasestorage.app',
    measurementId: 'G-Y05QJPZMJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABaoBNqsmW6wV5HZpP0gNKodBwfmKtz1A',
    appId: '1:286265416101:android:86acdbced3bada09df304c',
    messagingSenderId: '286265416101',
    projectId: 'bahias-2ea5b',
    storageBucket: 'bahias-2ea5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALoZiaKMabpCAkrot5h0T2M4KsQng_B2E',
    appId: '1:286265416101:ios:eb38f6ac624bab6ddf304c',
    messagingSenderId: '286265416101',
    projectId: 'bahias-2ea5b',
    storageBucket: 'bahias-2ea5b.firebasestorage.app',
    iosClientId: '286265416101-0gr9f58dfhgq8ve2l2bffagou2ed5o6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.bahiasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALoZiaKMabpCAkrot5h0T2M4KsQng_B2E',
    appId: '1:286265416101:ios:eb38f6ac624bab6ddf304c',
    messagingSenderId: '286265416101',
    projectId: 'bahias-2ea5b',
    storageBucket: 'bahias-2ea5b.firebasestorage.app',
    iosClientId: '286265416101-0gr9f58dfhgq8ve2l2bffagou2ed5o6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.bahiasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA55bEINystWICTNVd25nZI7Zodk9WCCYs',
    appId: '1:286265416101:web:6867a0a28a69e540df304c',
    messagingSenderId: '286265416101',
    projectId: 'bahias-2ea5b',
    authDomain: 'bahias-2ea5b.firebaseapp.com',
    storageBucket: 'bahias-2ea5b.firebasestorage.app',
    measurementId: 'G-TG9E39Q109',
  );
}
