name: Run init.sh on self-hosted runner
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]  # etiquetas del runner
    steps:
      - name: Ejecutar init.sh localmente
        run: |
              whoami
              cd /opt/repositorio/bahias-front/
              git pull origin main
              docker compose build
              docker compose down 
              docker compose up -d
              docker builder prune -f 
              docker image prune -f
              echo "Despliegue completado"
