name: Run init.sh on self-hosted runner
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]  # etiquetas del runner
    steps:
      - name: Actualizar código
        working-directory: /opt/repositorio/bahias-front/
        run: git pull origin main

      - name: Construir contenedores
        working-directory: /opt/repositorio/bahias-front/
        run: docker compose build

      - name: Reiniciar servicios
        working-directory: /opt/repositorio/bahias-front/
        run: |
          docker compose down
          docker compose up -d

      - name: Limpieza de imágenes
        run: |
          docker builder prune -f 
          docker image prune -f

      - name: Mensaje final
        run: echo "✅ Despliegue completado"
