name: Run init.sh on self-hosted runner
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]  # etiquetas del runner
    steps:
      - name: Ejecutar init.sh localmente
        run: |
              whoami
              /opt/repositorio/bahias-front/init.sh